// Mock data dla Live Sales - BaseLinker → Sheets

const MOCK_DATA = {
    // Pola dla zamówień
    fieldsOrders: [
        // Podstawowe
        { field_key: 'order_id', label: 'ID zamówienia', group: 'Podstawowe', higher_plan: false },
        { field_key: 'date_add', label: 'Data dodania', group: 'Podstawowe', higher_plan: false },
        { field_key: 'order_status_id', label: 'Status', group: 'Podstawowe', higher_plan: false },
        { field_key: 'total_price', label: 'Suma brutto', group: 'Podstawowe', higher_plan: false },
        { field_key: 'currency', label: 'Waluta', group: 'Podstawowe', higher_plan: false },
        { field_key: 'payment_method', label: 'Metoda płatności', group: 'Podstawowe', higher_plan: false },
        { field_key: 'delivery_method', label: 'Metoda dostawy', group: 'Podstawowe', higher_plan: false },
        
        // Dane klienta
        { field_key: 'email', label: 'Email', group: 'Dane klienta', higher_plan: false },
        { field_key: 'phone', label: 'Telefon', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_fullname', label: 'Imię i nazwisko (dostawa)', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_company', label: 'Firma (dostawa)', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_address', label: 'Adres (dostawa)', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_city', label: 'Miasto (dostawa)', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_postcode', label: 'Kod pocztowy (dostawa)', group: 'Dane klienta', higher_plan: false },
        { field_key: 'delivery_country', label: 'Kraj (dostawa)', group: 'Dane klienta', higher_plan: false },
        
        // Finansowe (PRO)
        { field_key: 'invoice_fullname', label: 'Dane do faktury - Nazwa', group: 'Finansowe', higher_plan: true },
        { field_key: 'invoice_nip', label: 'NIP', group: 'Finansowe', higher_plan: true },
        { field_key: 'invoice_address', label: 'Adres (faktura)', group: 'Finansowe', higher_plan: true },
        { field_key: 'invoice_city', label: 'Miasto (faktura)', group: 'Finansowe', higher_plan: true },
        { field_key: 'invoice_postcode', label: 'Kod pocztowy (faktura)', group: 'Finansowe', higher_plan: true },
        
        // Zaawansowane (PRO)
        { field_key: 'user_comments', label: 'Komentarz klienta', group: 'Zaawansowane', higher_plan: true },
        { field_key: 'admin_comments', label: 'Komentarz wewnętrzny', group: 'Zaawansowane', higher_plan: true },
    ],

    // Pola dla produktów
    fieldsProducts: [
        // Podstawowe
        { field_key: 'product_id', label: 'ID produktu', group: 'Podstawowe', higher_plan: false },
        { field_key: 'name', label: 'Nazwa produktu', group: 'Podstawowe', higher_plan: false },
        { field_key: 'ean', label: 'EAN', group: 'Podstawowe', higher_plan: false },
        { field_key: 'sku', label: 'SKU', group: 'Podstawowe', higher_plan: false },
        { field_key: 'quantity', label: 'Ilość', group: 'Podstawowe', higher_plan: false },
        { field_key: 'price_brutto', label: 'Cena brutto', group: 'Podstawowe', higher_plan: false },
        
        // Magazyn
        { field_key: 'stock', label: 'Stan magazynowy', group: 'Magazyn', higher_plan: false },
        { field_key: 'location', label: 'Lokalizacja', group: 'Magazyn', higher_plan: false },
        { field_key: 'weight', label: 'Waga (kg)', group: 'Magazyn', higher_plan: false },
        
        // Szczegóły (PRO)
        { field_key: 'manufacturer', label: 'Producent', group: 'Szczegóły', higher_plan: true },
        { field_key: 'category', label: 'Kategoria', group: 'Szczegóły', higher_plan: true },
        { field_key: 'description', label: 'Opis', group: 'Szczegóły', higher_plan: true },
        
        // Finansowe (PRO)
        { field_key: 'tax_rate', label: 'Stawka VAT', group: 'Finansowe', higher_plan: true },
        { field_key: 'purchase_price', label: 'Cena zakupu', group: 'Finansowe', higher_plan: true },
        { field_key: 'profit_margin', label: 'Marża (%)', group: 'Finansowe', higher_plan: true },
    ],

    // Przykładowe zamówienia
    sampleOrders: [
        {
            order_id: '1001',
            date_add: '2026-01-06 10:23:15',
            order_status_id: '234562',
            total_price: '299.99',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'InPost Paczkomat',
            email: 'jan.kowalski@example.com',
            phone: '+48 123 456 789',
            delivery_fullname: 'Jan Kowalski',
            delivery_company: '',
            delivery_address: 'ul. Testowa 123',
            delivery_city: 'Warszawa',
            delivery_postcode: '00-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Jan Kowalski',
            invoice_nip: '1234567890',
            invoice_address: 'ul. Testowa 123',
            invoice_city: 'Warszawa',
            invoice_postcode: '00-001',
            user_comments: 'Proszę o szybką realizację',
            admin_comments: 'Priorytetowe'
        },
        {
            order_id: '1002',
            date_add: '2026-01-06 11:45:22',
            order_status_id: '234563',
            total_price: '149.50',
            currency: 'PLN',
            payment_method: 'PayU',
            delivery_method: 'Kurier DPD',
            email: 'anna.nowak@example.com',
            phone: '+48 987 654 321',
            delivery_fullname: 'Anna Nowak',
            delivery_company: 'Firma ABC Sp. z o.o.',
            delivery_address: 'al. Solidarności 45',
            delivery_city: 'Kraków',
            delivery_postcode: '30-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Firma ABC Sp. z o.o.',
            invoice_nip: '9876543210',
            invoice_address: 'al. Solidarności 45',
            invoice_city: 'Kraków',
            invoice_postcode: '30-001',
            user_comments: '',
            admin_comments: 'Standard'
        },
        {
            order_id: '1003',
            date_add: '2026-01-06 12:15:33',
            order_status_id: '234540',
            total_price: '89.99',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'Odbiór osobisty',
            email: 'piotr.wisniewski@example.com',
            phone: '+48 111 222 333',
            delivery_fullname: 'Piotr Wiśniewski',
            delivery_company: '',
            delivery_address: 'ul. Kwiatowa 7',
            delivery_city: 'Gdańsk',
            delivery_postcode: '80-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Piotr Wiśniewski',
            invoice_nip: '',
            invoice_address: 'ul. Kwiatowa 7',
            invoice_city: 'Gdańsk',
            invoice_postcode: '80-001',
            user_comments: 'Dziękuję!',
            admin_comments: ''
        },
        {
            order_id: '1004',
            date_add: '2026-01-06 13:30:44',
            order_status_id: '234564',
            total_price: '499.00',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'InPost Kurier',
            email: 'maria.kowalczyk@example.com',
            phone: '+48 444 555 666',
            delivery_fullname: 'Maria Kowalczyk',
            delivery_company: '',
            delivery_address: 'ul. Polna 89',
            delivery_city: 'Poznań',
            delivery_postcode: '60-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Maria Kowalczyk',
            invoice_nip: '',
            invoice_address: 'ul. Polna 89',
            invoice_city: 'Poznań',
            invoice_postcode: '60-001',
            user_comments: '',
            admin_comments: 'Wysłane'
        },
        {
            order_id: '1005',
            date_add: '2026-01-06 14:20:55',
            order_status_id: '234562',
            total_price: '199.99',
            currency: 'PLN',
            payment_method: 'PayPal',
            delivery_method: 'Poczta Polska',
            email: 'tomasz.lewandowski@example.com',
            phone: '+48 777 888 999',
            delivery_fullname: 'Tomasz Lewandowski',
            delivery_company: '',
            delivery_address: 'ul. Słoneczna 15',
            delivery_city: 'Wrocław',
            delivery_postcode: '50-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Tomasz Lewandowski',
            invoice_nip: '5555555555',
            invoice_address: 'ul. Słoneczna 15',
            invoice_city: 'Wrocław',
            invoice_postcode: '50-001',
            user_comments: 'Proszę o paczkę ekologiczną',
            admin_comments: 'Notatka: klient VIP'
        },
        {
            order_id: '1006',
            date_add: '2026-01-06 15:10:11',
            order_status_id: '234540',
            total_price: '349.50',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'InPost Paczkomat',
            email: 'ewa.wojcik@example.com',
            phone: '+48 222 333 444',
            delivery_fullname: 'Ewa Wójcik',
            delivery_company: '',
            delivery_address: 'ul. Zielona 34',
            delivery_city: 'Łódź',
            delivery_postcode: '90-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Ewa Wójcik',
            invoice_nip: '',
            invoice_address: 'ul. Zielona 34',
            invoice_city: 'Łódź',
            invoice_postcode: '90-001',
            user_comments: '',
            admin_comments: 'Nowe zamówienie'
        },
        {
            order_id: '1007',
            date_add: '2026-01-06 16:05:22',
            order_status_id: '234563',
            total_price: '129.00',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'Kurier DPD',
            email: 'krzysztof.kaminski@example.com',
            phone: '+48 555 666 777',
            delivery_fullname: 'Krzysztof Kamiński',
            delivery_company: 'Tech Solutions',
            delivery_address: 'ul. Biznesowa 56',
            delivery_city: 'Katowice',
            delivery_postcode: '40-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Tech Solutions Sp. z o.o.',
            invoice_nip: '7777777777',
            invoice_address: 'ul. Biznesowa 56',
            invoice_city: 'Katowice',
            invoice_postcode: '40-001',
            user_comments: 'Faktura VAT',
            admin_comments: 'B2B'
        },
        {
            order_id: '1008',
            date_add: '2026-01-06 17:25:33',
            order_status_id: '234562',
            total_price: '79.99',
            currency: 'PLN',
            payment_method: 'PayU',
            delivery_method: 'InPost Paczkomat',
            email: 'magdalena.zielinska@example.com',
            phone: '+48 888 999 000',
            delivery_fullname: 'Magdalena Zielińska',
            delivery_company: '',
            delivery_address: 'ul. Krótka 3',
            delivery_city: 'Szczecin',
            delivery_postcode: '70-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Magdalena Zielińska',
            invoice_nip: '',
            invoice_address: 'ul. Krótka 3',
            invoice_city: 'Szczecin',
            invoice_postcode: '70-001',
            user_comments: 'Dziękuję',
            admin_comments: ''
        },
        {
            order_id: '1009',
            date_add: '2026-01-06 18:40:44',
            order_status_id: '234540',
            total_price: '259.00',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'Poczta Polska',
            email: 'adam.szymanski@example.com',
            phone: '+48 333 444 555',
            delivery_fullname: 'Adam Szymański',
            delivery_company: '',
            delivery_address: 'ul. Długa 78',
            delivery_city: 'Bydgoszcz',
            delivery_postcode: '85-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Adam Szymański',
            invoice_nip: '3333333333',
            invoice_address: 'ul. Długa 78',
            invoice_city: 'Bydgoszcz',
            invoice_postcode: '85-001',
            user_comments: '',
            admin_comments: 'Standardowa realizacja'
        },
        {
            order_id: '1010',
            date_add: '2026-01-06 19:15:55',
            order_status_id: '234564',
            total_price: '399.99',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'Kurier DPD',
            email: 'karolina.wojcik@example.com',
            phone: '+48 666 777 888',
            delivery_fullname: 'Karolina Wójcik',
            delivery_company: '',
            delivery_address: 'ul. Nowa 12',
            delivery_city: 'Lublin',
            delivery_postcode: '20-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Karolina Wójcik',
            invoice_nip: '',
            invoice_address: 'ul. Nowa 12',
            invoice_city: 'Lublin',
            invoice_postcode: '20-001',
            user_comments: 'Ekspresowa wysyłka mile widziana',
            admin_comments: 'Priorytet'
        },
        {
            order_id: '1011',
            date_add: '2026-01-06 20:30:10',
            order_status_id: '234562',
            total_price: '179.50',
            currency: 'PLN',
            payment_method: 'PayPal',
            delivery_method: 'InPost Paczkomat',
            email: 'pawel.kowalski@example.com',
            phone: '+48 111 222 333',
            delivery_fullname: 'Paweł Kowalski',
            delivery_company: '',
            delivery_address: 'ul. Słoneczna 99',
            delivery_city: 'Gdynia',
            delivery_postcode: '81-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Paweł Kowalski',
            invoice_nip: '',
            invoice_address: 'ul. Słoneczna 99',
            invoice_city: 'Gdynia',
            invoice_postcode: '81-001',
            user_comments: '',
            admin_comments: 'OK'
        },
        {
            order_id: '1012',
            date_add: '2026-01-06 21:05:25',
            order_status_id: '234563',
            total_price: '549.00',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'InPost Kurier',
            email: 'zofia.mazur@example.com',
            phone: '+48 444 555 666',
            delivery_fullname: 'Zofia Mazur',
            delivery_company: 'Design Studio',
            delivery_address: 'ul. Artystyczna 21',
            delivery_city: 'Rzeszów',
            delivery_postcode: '35-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Design Studio',
            invoice_nip: '8888888888',
            invoice_address: 'ul. Artystyczna 21',
            invoice_city: 'Rzeszów',
            invoice_postcode: '35-001',
            user_comments: 'Proszę o staranną paczkę',
            admin_comments: 'B2B - firma'
        },
        {
            order_id: '1013',
            date_add: '2026-01-06 21:45:40',
            order_status_id: '234540',
            total_price: '99.99',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'Poczta Polska',
            email: 'marcin.krawczyk@example.com',
            phone: '+48 777 888 999',
            delivery_fullname: 'Marcin Krawczyk',
            delivery_company: '',
            delivery_address: 'ul. Cicha 5',
            delivery_city: 'Toruń',
            delivery_postcode: '87-100',
            delivery_country: 'Polska',
            invoice_fullname: 'Marcin Krawczyk',
            invoice_nip: '',
            invoice_address: 'ul. Cicha 5',
            invoice_city: 'Toruń',
            invoice_postcode: '87-100',
            user_comments: '',
            admin_comments: 'Nowe'
        },
        {
            order_id: '1014',
            date_add: '2026-01-06 22:10:15',
            order_status_id: '234562',
            total_price: '219.00',
            currency: 'PLN',
            payment_method: 'PayU',
            delivery_method: 'InPost Paczkomat',
            email: 'natalia.piotrowska@example.com',
            phone: '+48 222 333 444',
            delivery_fullname: 'Natalia Piotrowska',
            delivery_company: '',
            delivery_address: 'ul. Główna 67',
            delivery_city: 'Białystok',
            delivery_postcode: '15-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Natalia Piotrowska',
            invoice_nip: '',
            invoice_address: 'ul. Główna 67',
            invoice_city: 'Białystok',
            invoice_postcode: '15-001',
            user_comments: 'Super sklep!',
            admin_comments: 'Zadowolony klient'
        },
        {
            order_id: '1015',
            date_add: '2026-01-06 22:35:50',
            order_status_id: '234563',
            total_price: '329.50',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'Kurier DPD',
            email: 'michal.grabowski@example.com',
            phone: '+48 555 666 777',
            delivery_fullname: 'Michał Grabowski',
            delivery_company: '',
            delivery_address: 'ul. Parkowa 44',
            delivery_city: 'Olsztyn',
            delivery_postcode: '10-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Michał Grabowski',
            invoice_nip: '4444444444',
            invoice_address: 'ul. Parkowa 44',
            invoice_city: 'Olsztyn',
            invoice_postcode: '10-001',
            user_comments: '',
            admin_comments: 'W realizacji'
        },
        {
            order_id: '1016',
            date_add: '2026-01-05 09:15:20',
            order_status_id: '234564',
            total_price: '159.99',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'InPost Paczkomat',
            email: 'beata.nowacka@example.com',
            phone: '+48 888 999 000',
            delivery_fullname: 'Beata Nowacka',
            delivery_company: '',
            delivery_address: 'ul. Różana 88',
            delivery_city: 'Kielce',
            delivery_postcode: '25-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Beata Nowacka',
            invoice_nip: '',
            invoice_address: 'ul. Różana 88',
            invoice_city: 'Kielce',
            invoice_postcode: '25-001',
            user_comments: '',
            admin_comments: 'Wysłane wczoraj'
        },
        {
            order_id: '1017',
            date_add: '2026-01-05 14:20:35',
            order_status_id: '234564',
            total_price: '449.00',
            currency: 'PLN',
            payment_method: 'PayPal',
            delivery_method: 'Kurier DPD',
            email: 'robert.duda@example.com',
            phone: '+48 333 444 555',
            delivery_fullname: 'Robert Duda',
            delivery_company: 'IT Group',
            delivery_address: 'ul. Technologiczna 100',
            delivery_city: 'Zielona Góra',
            delivery_postcode: '65-001',
            delivery_country: 'Polska',
            invoice_fullname: 'IT Group Sp. z o.o.',
            invoice_nip: '9999999999',
            invoice_address: 'ul. Technologiczna 100',
            invoice_city: 'Zielona Góra',
            invoice_postcode: '65-001',
            user_comments: 'B2B',
            admin_comments: 'Wysłane, śledzenie: ABC123'
        },
        {
            order_id: '1018',
            date_add: '2026-01-05 18:45:50',
            order_status_id: '234562',
            total_price: '189.99',
            currency: 'PLN',
            payment_method: 'Karta',
            delivery_method: 'InPost Paczkomat',
            email: 'aleksandra.kacprzak@example.com',
            phone: '+48 666 777 888',
            delivery_fullname: 'Aleksandra Kacprzak',
            delivery_company: '',
            delivery_address: 'ul. Wiosenna 23',
            delivery_city: 'Gorzów Wielkopolski',
            delivery_postcode: '66-400',
            delivery_country: 'Polska',
            invoice_fullname: 'Aleksandra Kacprzak',
            invoice_nip: '',
            invoice_address: 'ul. Wiosenna 23',
            invoice_city: 'Gorzów Wielkopolski',
            invoice_postcode: '66-400',
            user_comments: '',
            admin_comments: 'Opłacone'
        },
        {
            order_id: '1019',
            date_add: '2026-01-04 11:30:15',
            order_status_id: '234564',
            total_price: '279.50',
            currency: 'PLN',
            payment_method: 'Przelew',
            delivery_method: 'Poczta Polska',
            email: 'damian.wieczorek@example.com',
            phone: '+48 111 222 333',
            delivery_fullname: 'Damian Wieczorek',
            delivery_company: '',
            delivery_address: 'ul. Leśna 14',
            delivery_city: 'Opole',
            delivery_postcode: '45-001',
            delivery_country: 'Polska',
            invoice_fullname: 'Damian Wieczorek',
            invoice_nip: '',
            invoice_address: 'ul. Leśna 14',
            invoice_city: 'Opole',
            invoice_postcode: '45-001',
            user_comments: 'Dziękuję za szybką realizację',
            admin_comments: 'Wysłane 2 dni temu'
        },
        {
            order_id: '1020',
            date_add: '2026-01-04 16:55:40',
            order_status_id: '234564',
            total_price: '599.00',
            currency: 'PLN',
            payment_method: 'PayU',
            delivery_method: 'Kurier DPD',
            email: 'julia.gorska@example.com',
            phone: '+48 444 555 666',
            delivery_fullname: 'Julia Górska',
            delivery_company: '',
            delivery_address: 'ul. Górska 77',
            delivery_city: 'Elbląg',
            delivery_postcode: '82-300',
            delivery_country: 'Polska',
            invoice_fullname: 'Julia Górska',
            invoice_nip: '6666666666',
            invoice_address: 'ul. Górska 77',
            invoice_city: 'Elbląg',
            invoice_postcode: '82-300',
            user_comments: '',
            admin_comments: 'Dostarczono wczoraj'
        }
    ],

    // Przykładowe produkty
    sampleProducts: [
        {
            product_id: '5001',
            name: 'Klawiatura mechaniczna RGB',
            ean: '5901234567890',
            sku: 'KB-RGB-001',
            quantity: '45',
            price_brutto: '299.00',
            stock: '45',
            location: 'A-12-3',
            weight: '0.85',
            manufacturer: 'TechPro',
            category: 'Komputery > Klawiatury',
            description: 'Profesjonalna klawiatura mechaniczna z podświetleniem RGB',
            tax_rate: '23',
            purchase_price: '180.00',
            profit_margin: '39.67'
        },
        {
            product_id: '5002',
            name: 'Mysz bezprzewodowa',
            ean: '5901234567891',
            sku: 'MS-WL-002',
            quantity: '120',
            price_brutto: '89.99',
            stock: '120',
            location: 'A-12-4',
            weight: '0.15',
            manufacturer: 'TechPro',
            category: 'Komputery > Myszki',
            description: 'Ergonomiczna mysz bezprzewodowa',
            tax_rate: '23',
            purchase_price: '45.00',
            profit_margin: '50.00'
        },
        {
            product_id: '5003',
            name: 'Monitor 27" Full HD',
            ean: '5901234567892',
            sku: 'MON-27-003',
            quantity: '28',
            price_brutto: '799.00',
            stock: '28',
            location: 'B-05-1',
            weight: '5.50',
            manufacturer: 'ViewMaster',
            category: 'Komputery > Monitory',
            description: 'Monitor 27 cali Full HD IPS',
            tax_rate: '23',
            purchase_price: '520.00',
            profit_margin: '34.91'
        },
        {
            product_id: '5004',
            name: 'Słuchawki gamingowe',
            ean: '5901234567893',
            sku: 'HS-GM-004',
            quantity: '67',
            price_brutto: '199.99',
            stock: '67',
            location: 'A-14-2',
            weight: '0.35',
            manufacturer: 'AudioMax',
            category: 'Audio > Słuchawki',
            description: 'Słuchawki gamingowe z mikrofonem',
            tax_rate: '23',
            purchase_price: '110.00',
            profit_margin: '44.99'
        },
        {
            product_id: '5005',
            name: 'Kamera internetowa 1080p',
            ean: '5901234567894',
            sku: 'CAM-HD-005',
            quantity: '89',
            price_brutto: '149.00',
            stock: '89',
            location: 'A-15-1',
            weight: '0.25',
            manufacturer: 'VisionTech',
            category: 'Komputery > Kamery',
            description: 'Kamera Full HD z autofokusem',
            tax_rate: '23',
            purchase_price: '85.00',
            profit_margin: '42.94'
        },
        {
            product_id: '5006',
            name: 'Dysk SSD 1TB',
            ean: '5901234567895',
            sku: 'SSD-1T-006',
            quantity: '156',
            price_brutto: '349.00',
            stock: '156',
            location: 'C-08-3',
            weight: '0.08',
            manufacturer: 'StoragePro',
            category: 'Komputery > Dyski',
            description: 'Szybki dysk SSD NVMe 1TB',
            tax_rate: '23',
            purchase_price: '220.00',
            profit_margin: '36.95'
        },
        {
            product_id: '5007',
            name: 'Pendrive 128GB USB 3.0',
            ean: '5901234567896',
            sku: 'USB-128-007',
            quantity: '234',
            price_brutto: '49.99',
            stock: '234',
            location: 'C-10-5',
            weight: '0.01',
            manufacturer: 'DataFast',
            category: 'Komputery > Pamięci USB',
            description: 'Szybki pendrive 128GB',
            tax_rate: '23',
            purchase_price: '25.00',
            profit_margin: '49.99'
        },
        {
            product_id: '5008',
            name: 'Hub USB-C 7w1',
            ean: '5901234567897',
            sku: 'HUB-7P-008',
            quantity: '78',
            price_brutto: '129.00',
            stock: '78',
            location: 'A-16-2',
            weight: '0.12',
            manufacturer: 'ConnectPro',
            category: 'Komputery > Akcesoria',
            description: 'Rozbudowany hub USB-C z HDMI',
            tax_rate: '23',
            purchase_price: '70.00',
            profit_margin: '45.74'
        },
        {
            product_id: '5009',
            name: 'Podkładka pod mysz XL',
            ean: '5901234567898',
            sku: 'PAD-XL-009',
            quantity: '345',
            price_brutto: '39.99',
            stock: '345',
            location: 'A-17-4',
            weight: '0.20',
            manufacturer: 'GameGear',
            category: 'Komputery > Akcesoria',
            description: 'Duża podkładka pod mysz 90x40cm',
            tax_rate: '23',
            purchase_price: '18.00',
            profit_margin: '54.98'
        },
        {
            product_id: '5010',
            name: 'Kabel HDMI 2.0 2m',
            ean: '5901234567899',
            sku: 'HDMI-2M-010',
            quantity: '567',
            price_brutto: '29.99',
            stock: '567',
            location: 'C-12-1',
            weight: '0.15',
            manufacturer: 'CablePro',
            category: 'Komputery > Kable',
            description: 'Wysokiej jakości kabel HDMI',
            tax_rate: '23',
            purchase_price: '12.00',
            profit_margin: '59.99'
        },
        {
            product_id: '5011',
            name: 'Ładowarka USB 65W GaN',
            ean: '5901234567800',
            sku: 'CHG-65W-011',
            quantity: '91',
            price_brutto: '119.00',
            stock: '91',
            location: 'A-18-3',
            weight: '0.18',
            manufacturer: 'PowerFast',
            category: 'Akcesoria > Ładowarki',
            description: 'Kompaktowa ładowarka GaN 65W',
            tax_rate: '23',
            purchase_price: '65.00',
            profit_margin: '45.38'
        },
        {
            product_id: '5012',
            name: 'Powerbank 20000mAh',
            ean: '5901234567801',
            sku: 'PB-20K-012',
            quantity: '134',
            price_brutto: '89.00',
            stock: '134',
            location: 'A-19-2',
            weight: '0.45',
            manufacturer: 'PowerPlus',
            category: 'Akcesoria > Powerbanki',
            description: 'Powerbank z szybkim ładowaniem',
            tax_rate: '23',
            purchase_price: '48.00',
            profit_margin: '46.08'
        },
        {
            product_id: '5013',
            name: 'Etui na laptop 15.6"',
            ean: '5901234567802',
            sku: 'BAG-156-013',
            quantity: '78',
            price_brutto: '69.99',
            stock: '78',
            location: 'D-03-1',
            weight: '0.30',
            manufacturer: 'BagMaster',
            category: 'Akcesoria > Torby',
            description: 'Wodoodporne etui na laptop',
            tax_rate: '23',
            purchase_price: '35.00',
            profit_margin: '49.99'
        },
        {
            product_id: '5014',
            name: 'Statyw do telefonu',
            ean: '5901234567803',
            sku: 'TRP-MOB-014',
            quantity: '212',
            price_brutto: '59.00',
            stock: '212',
            location: 'D-05-2',
            weight: '0.40',
            manufacturer: 'PhotoGear',
            category: 'Foto > Statywy',
            description: 'Statyw z pilotem Bluetooth',
            tax_rate: '23',
            purchase_price: '28.00',
            profit_margin: '52.54'
        },
        {
            product_id: '5015',
            name: 'Lampa LED USB biurkowa',
            ean: '5901234567804',
            sku: 'LAMP-USB-015',
            quantity: '156',
            price_brutto: '79.99',
            stock: '156',
            location: 'D-07-3',
            weight: '0.55',
            manufacturer: 'LightPro',
            category: 'Oświetlenie > Lampy',
            description: 'Regulowana lampa LED',
            tax_rate: '23',
            purchase_price: '42.00',
            profit_margin: '47.48'
        }
    ],

    // Lista eksportów
    exportsList: [
        {
            id: 'export-1',
            name: 'Zamówienia dzienne do Sheets',
            type: 'orders',
            interval: 15,
            sheets_tab: 'Sheet1',
            status: 'active',
            last_run: '2026-01-06 22:08:30',
            uptime: '99.8',
            sheet_url: 'https://docs.google.com/spreadsheets/d/1eakktbW8gttUOukkws3G7I2GBQo3DYzDdFls705pC5g/edit'
        },
        {
            id: 'export-2',
            name: 'Produkty - raport magazynowy',
            type: 'products',
            interval: 60,
            sheets_tab: 'Magazyn',
            status: 'active',
            last_run: '2026-01-06 21:45:00',
            uptime: '99.5',
            sheet_url: ''
        },
        {
            id: 'export-3',
            name: 'Zamówienia do pakowania',
            type: 'orders',
            interval: 5,
            sheets_tab: 'Pakowanie',
            status: 'paused',
            last_run: '2026-01-06 18:30:15',
            uptime: '98.9',
            sheet_url: ''
        }
    ]
};
